(function(){
'use strict';
const THEME_KEY='jmh-theme';
function getPreferredTheme(){const s=localStorage.getItem(THEME_KEY);return s||'dark';}
function setTheme(t){document.documentElement.setAttribute('data-theme',t);localStorage.setItem(THEME_KEY,t);updateThemeIcon(t);}
function updateThemeIcon(t){const b=document.querySelector('.theme-toggle');if(!b)return;b.innerHTML=t==='dark'?'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>':'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';b.setAttribute('aria-label',t==='dark'?'Switch to light mode':'Switch to dark mode');}
function toggleTheme(){const c=document.documentElement.getAttribute('data-theme')||'dark';setTheme(c==='dark'?'light':'dark');}
setTheme(getPreferredTheme());
function initMobileNav(){const toggle=document.querySelector('.nav-menu-toggle'),links=document.querySelector('.nav-links');if(!toggle||!links)return;const backdrop=document.createElement('div');backdrop.className='nav-backdrop';document.body.appendChild(backdrop);const ICON_X='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>';const ICON_BURGER='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="18" x2="21" y2="18"/></svg>';function openMenu(){links.classList.add('open');backdrop.classList.add('active');toggle.setAttribute('aria-expanded','true');toggle.innerHTML=ICON_X;}function closeMenu(){links.classList.remove('open');backdrop.classList.remove('active');toggle.setAttribute('aria-expanded','false');toggle.innerHTML=ICON_BURGER;}toggle.addEventListener('click',()=>{links.classList.contains('open')?closeMenu():openMenu();});backdrop.addEventListener('click',closeMenu);links.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));}
function setActiveNavLink(){const path=window.location.pathname.replace(/\/$/,'')||'/';document.querySelectorAll('.nav-links a').forEach(a=>{if(!a.href)return;try{const lp=new URL(a.href).pathname.replace(/\/$/,'')||'/';if(path===lp||(lp!=='/'&&path.startsWith(lp)))a.classList.add('active');}catch(e){}});}
function initScrollReveal(){const els=document.querySelectorAll('.reveal');if(!els.length)return;const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target);}});},{threshold:0,rootMargin:'0px 0px -50px 0px'});els.forEach(el=>obs.observe(el));}
function initScrollProgress(){const bar=document.querySelector('.scroll-progress');if(!bar)return;function u(){const st=window.scrollY,dh=document.documentElement.scrollHeight-window.innerHeight,p=dh>0?(st/dh)*100:0;bar.style.width=p+'%';}window.addEventListener('scroll',u,{passive:true});u();}
function initSmoothScroll(){document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener('click',e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth',block:'start'});}});});}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.theme-toggle').forEach(b=>b.addEventListener('click',toggleTheme));initMobileNav();setActiveNavLink();initScrollReveal();initScrollProgress();initSmoothScroll();});
})();
